weka-io/easypy

- easypy/concurrency.py
- easypy/logging.py
- easypy/threadtree.py
- tests/conftest.py
- tests/test_concurrency.py
feel free to suggest alternate names there
> threadtree: refactor logging's Context into ThreadContext

- easypy/signals.py
A method might belong to an object that _isn't_ linked 1-to-1 with the subject of a signal.
For example, the RTFSController wants to get notified `on_before_machine_reboot`, but doesn't have a `machine` attribute.
> signals with identifiers: clarifying when the handler would be called

- easypy/collections.py
- tests/test_collections.py
Indeed this algorithm can grow quickly, but in our common case when uniquifying on a single attribute it should be O(sane)...
> collections: support for 'attr=UNIQUE' when sampling items 

- .travis.yml
- easypy/bunch.py
- tests/test_bunch.py
we may use this for various configuration structs
> bunch: make it rigid by defining KEYS

- easypy/__init__.py
- easypy/concurrency.py
- easypy/gevent.py
- easypy/humanize.py
- easypy/threadtree.py
- tests/conftest.py
- tests/test_concurrency.py
* hogging detection for gevent greenlets
* dump threads run in a real thread
(still work in progress - there's a problem with `./teka.py logs`, regardless of the PAGER)
> gevent: support real threads with monkey patching. Also:

- easypy/concurrency.py
- tests/conftest.py
- tests/test_concurrency.py
Would appreciate your careful review, in light of WEKAPP-36360
> concurrency: bug fix LoggedRLock use of lease timer

- easypy/lockstep.py
- tests/test_lockstep.py
Assuming:
```python
class Foo:
@lockstep
def process(self):
foo = Foo()
```
* `foo.process()` - run the entire process
* `with foo.process.lockstep() as process:` - step into the process
* `yield from foo.process.lockstep()` - for lockstep nesting
> Close #13 - better lockstep API

- easypy/caching.py
- tests/test_caching.py
sometimes a cached function can get some extra params that help it calc the value, but aren't necessarily part of the key for their cache.
> caching: support for ignored kwargs in func-caching decorators

- easypy/concurrency.py
- tests/test_synchronization_coordinator.py
@koreno - before I start testing it with testlight (which will increase the cycles) please approve the design.
> Concurrency synchronization coordinator

- easypy/concurrency.py
- tests/test_concurrency.py
https://wekaio.atlassian.net/browse/WEKAPP-58333
> Make `nonconcurrent_map` use `Future`

- easypy/concurrency.py
- tests/test_concurrency.py
Note that unlike `LoggedRLock`, no one is owning the condition while the waiters wait for it - so there is no point in logging the "number of owners".
> Add logged condition

- CONTRIBUTING.md
- README.md
https://github.com/weka-io/easypy/blob/add-contribution-md-with-reStructuredText-cheatsheet/CONTRIBUTING.md
> Add `CONTRIBUTING.md` with basic reStructuredText cheatsheet

- easypy/concurrency.py
- tests/test_concurrency.py
> concurrency: and now make MultiObject typeable too

- easypy/concurrency.py
- tests/test_concurrency.py
- tests/test_synchronization_coordinator.py
> BREAKING CHANGE - concurrency: make MultiObject immutable; remove list operators

- easypy/typed_struct.py
Just a little something that annoyed me when I was working with S0 and SpecSFS configurations in `teka explore`.
Before:
```python
In [2]: class Foo(TypedStruct):
...:     a = int
...:     a.default = 12
...:     b = str
...:     
In [3]: Foo?
Init signature: Foo(**kwargs)
Docstring:      <no docstring>
File:           /files/code/wekapp/subcommands/explore.py
Type:           TypedStructMeta
In [4]: Foo._fields
Out[4]: 
[<easypy.typed_struct.Field at 0x7f5a177d0518>,
<easypy.typed_struct.Field at 0x7f5a177d0320>]
```
After:
```python
In [2]: class Foo(TypedStruct):
...:     a = int
...:     a.default = 12
...:     b = str
...:
In [3]: Foo?
Init signature: Foo(*, a:int=12, b:str)
File:           /files/code/easypy/easypy/typed_struct.py
Type:           TypedStructMeta
In [4]: Foo._fields …
```
> Better IPython representation of `TypeStruct` classes

- easypy/logging.py
This fixes a bug where a record was being handles by the ContextHandler more than once,
as the handler was found on more than one logger in the loggers chain.
> logging: refactor ContextHandler logic into makeLogRecord

- easypy/concurrency.py
- easypy/logging.py
wanted this to suppress logging from bg thread while AppMenu is showing its UI
> logging: support for suppressing and soloing logging to console per thread

- CHANGELOG.md
- easypy/collections.py
This came up a bunch of times...
> collections: added 'takesome'

- easypy/collections.py
- tests/test_collections.py
- support naming collections
- improve repr
- support ipython pretty repr
> collections: raise informative exceptions when object-not-found (#142)

- easypy/resilience.py
> resilience: Add 'unacceptable' arg to 'retrying'

- .travis.yml
- easypy/concurrency.py
- easypy/logging.py
- easypy/sync.py
- test_package.py
- tests/test_concurrency.py
- tests/test_sync.py
turned out if you import things in the wrong order you get an import error...
> Prevent import cycles

- easypy/resilience.py
> resilience: Fix 'retry' docstring.

- easypy/concurrency.py
> concurrency: Add parent's name to new thread's name

- easypy/semver.py
- tests/test_semver.py
We need this module available in other projects. I lost track to where should we push this. `master` / one of the `wekapp` branches. I will also need this in a released package and I saw some effort to release a `0.4.0` what is the status of that?
> Add semver module

- CHANGELOG.md
- easypy/timing.py
- easypy/units.py
- tests/test_timing.py
and support for comparing Timers with time-based types
> timing/units: added a TimeInterval class

- CHANGELOG.md
- easypy/decorations.py
- tests/test_decorations.py
As I suggested in #185 - here is my implementation of `ensure_same_defaults`.
> Add `ensure_same_defaults`
