easypy/lockstep.py
tests/test_lockstep.py

@koreno - I want to use this for the installation tests. Instead of using a bare generator and hoping we counted the `yield`s and and `next` correctly and in sync, a `step_by_step` will allow us to enforce that the installation step the test thinks we are at is the same step the infra says we are at.

Step by step

---

easypy/decorations.py
tests/test_decorations.py

We can use `@deprecated` to safely rename functions and fix calls to
them based on the deprecation warnings. This decorator does the same
thing for function arguments.

Add `deprecated_arguments` decorator.

---

easypy/bunch.py
tests/test_bunch.py

`__setitem__` in `Bunch` checks the opposite of what we want. Fixing that fails other stuff because we should only check if `KEYS` is set.
Also added assignment tests to uts.

bunch: fix checks in bunch when KEYS is set

---

easypy/timing.py
tests/test_timing.py

Basically this moves the expiration check to before running the
predicate, to avoid the following scenario:
1. Predicate checks the condition.
2. Something the predicate function does after that takes very long.
3. Some times passes.
4. The actual condition becomes true(not checked yet)
5. Some more time passes.
6. The predicate function finishes whatever it was doing and returns.
7. TIMEOUT!
This change makes sure that no matter how long the predicate takes, as
long as the condition becomes true **before** the expiration time the
predicate will have a chance to check it and return True.

Allow `iter_wait` to handle long predicates

---

.travis.yml
easypy/humanize.py
easypy/typed_struct.py
tests/test_typed_struct.py

* Simple definition syntax - without repeating field names.
* Short syntax for simple fields - workds with IDE completion.
* Full `ts.Field(...)` syntax to define default value, validators etc.
* `meta` field that can be used to provide metadata for reflection.
* Support for typechecked `list`, `dict` and `Bunch` fields.
Future plans(will need more design):
* Hooks/signals for doing things when users change the fields.
* Bubble up? Parent `TypedStruct`'s hook get activated when
fields of nested `TypedStruct`s are changed?

Close #38: Add `TypedStruct`

---

easypy/concurrency.py
tests/test_concurrency.py

The race - "_T_" is the `TagAlongThread`, "_C_" is the caller thread:
- _T_ waits on `_iteration_trigger`.
- _C_ sets `_iteration_trigger`.
- _T_ sets `_iterating`.
- _T_ performs the loop too fast - before _C_ has a chance to do anything.
- _T_ clears `_iterating`.
- _C_ waits on `_iterating`.
- _T_ starts over again - and waits on `_iteration_trigger`.
_C_ is waiting for _T_ to set `_iterating` - but _T_ has already set it
and cleared it, and won't set it again until someone else sets
`_iteration_trigger`. This may never happen because _C_ is stuck and the
program can't progress...
The solution that every second _C_ will look at `_not_iterating` - an
`Event` that we already have for a different purpose and gets set after
the iteration is done.
Now, in theory, a deadlock is still …

Fix a deadlock-causing race-condition in `TagAlongThread`:

---

easypy/timing.py
tests/test_timing.py

Currently the message we display when `wait` times out is generated
**before** the waiting. This means we can't write in it things related
to the state **after** the waiting.
This commit supports a lambda message, that will be invoked after the
timeout and thus can have up-to-date information in it.

Callable `wait` message

---

easypy/timezone.py
tests/test_timezone.py

- UTC timezone will be displayed as 'Z'.
- Named timezone will be displayed with their name(e.g. 'IST')
- Nameless timezones will be displayed with their offset(e.g. '+02:00')

Properly display timezone in `short_utc_fmt`

---

easypy/typed_struct.py
tests/test_typed_struct.py

To prevent things like this:
```python
In [1]: from easypy import typed_struct as ts
In [2]: class Foo(ts.TypedStruct):
...:     bars = [str]
...:
In [3]: Foo(bars='hello')
Out[3]:
Foo(bars=['h',
'e',
'l',
'l',
'o'])
```

Verify collection type in `TypedStruct`

---

easypy/timing.py
tests/test_timing.py

Use case: on the final attempt, if the predicate is still `False`, it
may want to print something to the log to help us determine what went
wrong. To avoid spamming the logs, we don't want to print it on every
iteration.

Let the predicate of `wait` know if it's the final attempt

---

easypy/concurrency.py
easypy/exceptions.py

There's a bunch of code duplication here, but it's too much to refactor at this stage. In other words, we're looking for bugs, not so much for code elegance...

concurrency: fix multiexception rendering to include timestamp and context; add timestamp exceptions if concurrent

---

easypy/typed_struct.py
tests/test_typed_struct.py

Previously, if you wanted to - for example - add a conversion to a
field, you'd have to do this:
```python
class Foo(ts.TypedStruct):
a = ts.Field(int)
a.convertible_from(str)
```
Or this:
```python
class Foo(ts.TypedStruct):
a = int
Foo.a.convertible_from(str)
```
With this commit, you can do this:
```python
class Foo(ts.TypedStruct):
a = int
a.convertible_from(str)
```
This is the first step of a better `TypedStruct` API that I'm planning. For the next step, I want to support things like this:
```python
class Foo(TypedStruct):
with convertible_from(int, float, str):
a = int
b = float
c = [int]
```
Note that currently we do things like this:
```python
def numeric_field(field_type, **kwargs):
field = ts.Field(field_type, **kwargs)
field.add_conversion(int, float, str)
return field
class …
```

Automatically convert fields in `TypedStruct` definition to `Field`

---

easypy/concurrency.py
tests/test_concurrency.py

- use thread name instead of thread-ident
- fix lookup of frame when waiting on Futures
- find a useful frame, non-threading-related when reporting hanging Futures

concurrency: improve logging when waiting on threads

---

easypy/concurrency.py
tests/test_concurrency.py

This is to allow creation of a MultiException sub-type out of a type that
mixes a BaseException subclass with non-BaseException classes

concurrency: bug fix for MultiException of multi-inherited types

---

easypy/meta.py
tests/test_meta.py

Also add first mixin (constructor) that uses `EasyMeta`: `auto_registrar`.
This is a proof of concept for combinable meta mixins - in the future we will add more hooks that'll allow more mixins.
The syntax is a bit different than what I wrote in #80. I'm decorating the hooks with `EasyMeta.Hook`, and making the DSL (the dictionary used in the class declaration) "swallow" them - so that they won't appear in the actual class. This also means we don't need to fear several mixins using the same hook overwriting each other's work. But this also means I'll have to do something about hooks we can only have one of (e.g. hooks that replace instance creation). Still - better than having these hooks decided arbitrarily by the order of baseclass resolution...

Close #80: Add `EasyMeta` (for now with only one hook)

---

easypy/signals.py
tests/test_signals.py

We may not be able to solve the big leak, but this is definitely a bug!

Fix `Signal.unregister` for context manager signals

---

easypy/decorations.py
easypy/lockstep.py
easypy/signals.py
tests/test_signals.py

This makes signal handlers use weak references to methods so that they won't be keeping the objects alive.
Questions:
1. Do we want an opt-out argument?
2. Do we want to, instead of making `Signal.register()` convert methods to `WeakMethod`, have the conversion be done in `register_object` so that directly registered methods won't be weakly referenced?
* On the one hand, these are methods too and we don't want the globally scoped signal to keep their objects alive.
* On the other hand, one would usually register these methods with the `registered` context manager, so unregistration will be done automatically and weakreffing could be potentially harmful.

Signals handlers keep methods as weak references

---

easypy/caching.py
easypy/decorations.py
tests/test_decorations.py

This prevents the `singleton_contextmanager` from keeping it's arguments
alive (most importantly - `self` for methods) even after the
contextmanager has finished.

`singleton_contextmanager` remove from cache on `__exit__`

---

CHANGELOG.md
easypy/caching.py
tests/test_caching.py

Prevent `_TimeCache.__init__` from overriding the attributes it sets
with attributes of the wrapped function.

Fix `resilient` between `timecache`s

---

CHANGELOG.md
easypy/humanize.py
easypy/typed_struct.py
tests/test_typed_struct.py

* `repr` can configure how the field in represented in textual
representation of the typed struct.
* `hash` can configure how the field is considered when hashing the
typed struct.

Add `repr` and `hash` to typed struct fields

---

easypy/exceptions.py
tests/test_exceptions.py

shouldn't be a common practice, but we needed this to pass exception via rpyc...

exceptions: support pickling

---

easypy/collections.py
easypy/typed_struct.py
tests/test_collections.py

pretty esoteric, i would remove the sibling methods if we could, its too costly...

collections: workaround python bug importing 'test.support'

---

CHANGELOG.md
easypy/aliasing.py
tests/test_aliasing.py

Improve `RecursionError` for aliasing-induced infinite recursion
